[package]
name = "merge-sort"
version = "0.1.0"
authors = ["Wang Ruochen <wangkevin920@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
